Controllers/ExaminationsController.cs
using Avtotest.Web.Models;
using Avtotest.Web.Options;
using Avtotest.Web.Repositories;
using Avtotest.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Avtotest.Web.Controllers;

public class ExaminationsController : Controller
{
    private readonly QuestionsRepository _questionsRepository;
    private readonly UsersService _usersService;
    private readonly TicketsRepository _ticketsRepository;

    private readonly int TicketQuestionCount = 20;

    public ExaminationsController(
        QuestionsRepository questionsRepository,
        UsersService usersService,
        TicketsRepository ticketsRepository,
        IOptions<TicketSettings> option)
    {
        _questionsRepository = questionsRepository;
        _usersService = usersService;
        _ticketsRepository = ticketsRepository;
        TicketQuestionCount = option.Value.QuestionsCount;
    }

    public IActionResult Index()
    {
        var user = _usersService.GetUserFromCookie(HttpContext);
        if(user == null)
            return RedirectToAction("SignIn", "Users");

        var ticket = CreateRandomTicket(user);

        return View(ticket);
    }

    private Ticket CreateRandomTicket(User user)
    {
        //10 va 20 ni hisoblash kerak
        var ticketCount = _questionsRepository.GetQuestionsCount() / TicketQuestionCount;

        var random = new Random();
        var ticketIndex = random.Next(0, ticketCount);
        var from = ticketIndex * TicketQuestionCount;

        var ticket =  new Ticket(user.Index, from, TicketQuestionCount);

        _ticketsRepository.InsertTicket(ticket);

        var id = _ticketsRepository.GetLastRowId();
        ticket.Id = id;

        return ticket;
    }

    [Route("tickets/{ticketId}")]
    [Route("tickets/{ticketId}/questions/{questionId}")]
    [Route("tickets/{ticketId}/questions/{questionId}/choices/{choiceId}")]
    public IActionResult Exam(int ticketId, int? questionId = null, int? choiceId = null)
    {
        var user = _usersService.GetUserFromCookie(HttpContext);
        if (user == null)
            return RedirectToAction("SignIn", "Users");

        var ticket = _ticketsRepository.GetTicketById(ticketId, user.Index);

        questionId = questionId ?? ticket.FromIndex;

        if (ticket.FromIndex <= questionId && ticket.QuestionsCount + ticket.FromIndex > questionId)
        {
            var question = _questionsRepository.GetQuestionById(questionId.Value);

            ViewBag.TicketData = _ticketsRepository.GetTicketDataById(ticket.Id);

            //2, get from ticket_data by questionId and ticketId
            var _ticketData = _ticketsRepository.GetTicketDataByQuestionId(ticketId, questionId.Value);

            var _choiceId = (int?)null;
            var _answer = false;

            if (_ticketData != null)
            {
                _choiceId = _ticketData.ChoiceId;
                _answer = _ticketData.Answer;
            }
            else if (choiceId != null)
            {
                //1, insert into ticket_data ticketId, questionId, choiceId, answer;
                var answer = question.Choices!.First(choice => choice.Id == choiceId).Answer;
                
                var ticketData = new TicketData()
                {
                    TicketId = ticketId,
                    QuestionId = question.Id,
                    ChoiceId = choiceId.Value,
                    Answer = answer
                };
                _ticketsRepository.InsertTicketData(ticketData);
                
                _choiceId = choiceId;
                _answer = answer;

                //4, if answer true update ticket correct count
                if (_answer)
                {
                    _ticketsRepository.UpdateTicketCorrectCount(ticket.Id);
                }
                //3, agar hamma savolga javob bergan bolsa natijani korsatish
                if (ticket.QuestionsCount == _ticketsRepository.GetTicketAnswersCount(ticket.Id))
                {
                    return RedirectToAction("ExamResult", new {ticketId = ticket.Id});
                }
            }

            ViewBag.Ticket = ticket;
            ViewBag.ChoiceId = _choiceId;
            ViewBag.Answer = _answer;

            return View(question);
        }

        return NotFound();
    }

    public IActionResult GetQuestionById(int questionId)
    {
        var question = _questionsRepository.GetQuestionById(questionId);
        return View(question);
    }

    public IActionResult ExamResult(int ticketId)
    {
        var user = _usersService.GetUserFromCookie(HttpContext);
        if (user == null)
            return RedirectToAction("SignIn", "Users");

        var ticket = _ticketsRepository.GetTicketById(ticketId, user.Index);

        return View(ticket);
    }
}

Controllers/TicketsController.cs
using Avtotest.Web.Repositories;
using Avtotest.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace Avtotest.Web.Controllers;

public class TicketsController : Controller
{
    private readonly UsersService _usersService;
    private readonly TicketsRepository _ticketsRepository;

    public TicketsController(UsersService usersService, 
        TicketsRepository ticketsRepository)
    {
        _usersService = usersService;
        _ticketsRepository = ticketsRepository;
    }

    public IActionResult Index()
    {
        var user = _usersService.GetUserFromCookie(HttpContext);
        if (user == null)
            return RedirectToAction("SignIn", "Users");

        var tickets = _ticketsRepository.GetTicketsByUserId(user.Index);

        return View(tickets);
    }
}

Controllers/UsersController.cs
using Avtotest.Web.Models;
using Avtotest.Web.Repositories;
using Avtotest.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace Avtotest.Web.Controllers;

[Route("[action]")]
public class UsersController : Controller
{
    private readonly UsersRepository _usersRepository;
    private readonly CookiesService _cookiesService;
    private readonly UsersService _usersService;
    private readonly TicketsRepository _ticketsRepository;
    private readonly QuestionsRepository _questionsRepository;

    public UsersController(UsersRepository usersRepository,
        CookiesService cookiesService, 
        UsersService usersService,
        TicketsRepository ticketsRepository,
        QuestionsRepository questionsRepository)
    {
        _usersRepository = usersRepository;
        _cookiesService = cookiesService;
        _usersService = usersService;
        _ticketsRepository = ticketsRepository;
        _questionsRepository = questionsRepository;
    }

    public IActionResult Index()
    {
        var user = _usersService.GetUserFromCookie(HttpContext);
        if (user != null)
        {
            return View(user);
        }

        return RedirectToAction("SignIn");
    }

    public IActionResult SignUp()
    {
        return View();
    }

    [HttpPost]
    public IActionResult SignUp(User user)
    {
        if (!ModelState.IsValid)
        {
            return View(user);
        }

        user.Image ??= "sdadsa.png";
        _usersRepository.InsertUser(user);
        var _user = _usersRepository.GetUserByPhoneNumber(user.Phone!);

        _ticketsRepository.InsertUserTrainingTickets(_user.Index, _questionsRepository.GetQuestionsCount() / 20, 20);
        _cookiesService.SendUserPhoneToCookie(user.Phone!, HttpContext);
        return RedirectToAction("Index");
    }

    public IActionResult SignIn()
    {
        return View();
    }

    [HttpPost]
    public IActionResult SignIn(UserDto user)
    {
        if (!ModelState.IsValid)
        {
            return View(user);
        }

        var _user = _usersRepository.GetUserByPhoneNumber(user.Phone!);

        if (_user.Password == user.Password)
        {
            _cookiesService.SendUserPhoneToCookie(user.Phone!, HttpContext);
            return RedirectToAction("Index");
        }

        return RedirectToAction("SignIn");
    }

    public IActionResult Edit()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Edit([FromForm] User user)
    {
        var _user = _usersService.GetUserFromCookie(HttpContext);
        if (_user == null)
            return RedirectToAction("SignIn");
            
        user.Index = _user.Index;
        user.Image = SaveUserImage(user.ImageFile);
        _usersRepository.UpdateUser(user);
        return RedirectToAction("Index");
    }

    private string? SaveUserImage(IFormFile? userImageFile)
    {
        if (userImageFile == null)
        {
            return "avatar.png";
        }

        var imagePath = Guid.NewGuid().ToString("N") + Path.GetExtension(userImageFile.FileName);

        var ms = new MemoryStream();
        userImageFile.CopyTo(ms);
        System.IO.File.WriteAllBytes(Path.Combine("wwwroot", "Profile", imagePath), ms.ToArray());

        return imagePath;
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Avtoexam.uz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Avtotest.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow m-auto w-75">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Avtoexam</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Examinations" asp-action="Index">Examination</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
                        </li>
                    </ul>
                    <div>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Profile</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container w-75">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Avtotest.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>